apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: decaf-cluster
  region: us-west-2

vpc:
  subnets:
    public:
      us-west-2b: { id: subnet-03e50ae6f81515fb5 }
      us-west-2d: { id: subnet-03ad2a9994ca0de67 }
      us-west-2c: { id: subnet-0205a08881be05567 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 3
    ssh:
      publicKeyPath: ./keypair.pub
